spring.application.name=springLearn
logging.level.org.springframework=info
logging.level.com.cognizant.springLearn=debug

logging.pattern.console=%d{yyMMdd} %d{HH:mm:ss.SSS} %-20.20thread %-5level %logger{25} - %msg%n